### PR TITLE
Temporary health fix

### LINKED ISSUE #77: Pebble Health nag screen with Health disabled
Nag screen with occasionally pop up with this watchface. I have the Health features turned off on my watch, as I do not have the watch on 24/7. Had the same issue with another watchface, required some dev changes to remove access to the Heath features to resolve.

### PR DESCRIPTION
**Pull request by timothythlau**
This is a temp fix for the health nag screen issue, as described in #77. Reworked the logic so that the Pebble Health API is only queried when the toggle to vibrate every hour is enabled.

For a full fix, it looks like a switch is required in the config page to enable/disable the Pebble Health service API, something similar to what other watchfaces have done, such as this one: https://github.com/hussin/timeboxed-watchface
This seems like it would require the config page to also be updated, which is being hosted externally, so I cannot add the switch in for the required boolean property.

### CODE REVIEW

File: src/minimalin.c [hunk 1]
```diff
@@ -72,6 +72,12 @@ static GPoint SOUTH_INFO_CENTER = { .x = 72, .y = 112 };
 static GPoint NORTH_INFO_CENTER = { .x = 72, .y = 56 };
 #endif
 
+#ifdef PBL_HEALTH
```
Comment (timothythlau) [inline src/minimalin.c]: Note that this ifdef doesn't seem to reflect whether a user has enabled or disabled the Pebble Health service, but rather if the platform has it. Still worth keeping this in for all OG pebble users, but can be removed if the config page includes a switch to toggle Health API integration.

**Comment by groyoh** [comment]
Merged within https://github.com/groyoh/minimalin/commit/82dc176dcc0f3cc579c2f0de5fac40bbfdd55a05.
